### ISSUE TITLE
Android: Update project setup

### ISSUE THREAD

**Issue by TomasKypta** [wultra/powerauth-mobile-sdk#100]
Versions of various build tools are rather outdated, there are newer setups being used now.
The things to update are: android build plugin, gradle wrapper, build repositories.

**Comment by hvge** [comment]
Just make sure that `android-release-aar.gradle` will still work, because it's important for deployment to jcenter. The `scripts/deploy-build.sh` is internally calling `gradlew clean build generateRelease` to prepare a ZIP file with build. The ZIP must be prepared to specific path.
