### ISSUE TITLE
Android: Improve support annotations for SDK API

### ISSUE THREAD

**Issue by TomasKypta** [wultra/powerauth-mobile-sdk#102]
Add support annotations to help with proper usage of the SDK.
This mainly involves adding annotations denoting which thread should be a method called on: `@WorkerThread`, `@MainThread`, …

**Comment by hvge** [comment]
I think we should address this as a part for Crypto3 changes.

**Comment by petrdvorak** [comment]
Consider if we are able to make this for 2018.12 release...
