### ISSUE TITLE
Migration to new endpoint for signature validation

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-mobile-sdk#107]
We will introduce a new endpoint for signature validation in PA integration libraries:
https://github.com/lime-company/powerauth-restful-integration/issues/26

Once this change is published in a public release and there is enough time for clients to migrate to new PA server we should migrate to the new signature validation method in the SDK (e.g. for cases when  vault unlock is misused for signature validation).

**Comment by hvge** [comment]
Just for note, this will deprecate following vault unlock reasons: `"PASSWORD_VALIDATE"` & `"PASSWORD_CHANGE"`
