### ISSUE TITLE
Android: inconsistent @Nullable attribute in ISavePowerAuthStateListener

### ISSUE THREAD

**Issue by ForestTree** [wultra/powerauth-mobile-sdk#110]
Please remove inconsistent `@Nullable` attribute from **instanceId** parameter of `ISavePowerAuthStateListener` method `onPowerAuthStateChanged()`. I mean null String as instanceId value is now obsolete.

**Comment by petrdvorak** [comment]
@TomasKypta please have a look.

**Comment by hvge** [comment]
I guess, that we can change that to `@NonNull`, for both methods in that ifc. I can fix this, for planned `0.19.x`

@ForestTree I'm wondering how's this change important to you. Did you run some Analyser on the project?

**Comment by ForestTree** [comment]
Not important at this time. Please fix in some planned future version. Thanks!
