### ISSUE TITLE
Extend API for styling fingerprint dialog

### ISSUE THREAD

**Issue by TomasKypta** [wultra/powerauth-mobile-sdk#112]
Later versions of Android build plugin will not allow resources overriding.
Therefore styling API will be necessary for fingerprint dialog.

Note that in Android P the whole fingerprint API changes and the custom fingerprint dialog will be obsolete.

**Comment by hvge** [comment]
@TomasKypta is this still a thing? We have now [BiometricDialogResources](https://github.com/wultra/powerauth-mobile-sdk/blob/develop/proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricDialogResources.java), that can be configured globally and affects how the fingerprint dialog looks. Is this enough, or do we need to implement support for more customizations?

**Comment by TomasKypta** [comment]
I guess it's ok like this. Closing.
