### ISSUE TITLE
io.getlime.security.powerauth.networking.exceptions.ErrorResponseApiException

### ISSUE THREAD

**Issue by HoaiNam1105** [wultra/powerauth-mobile-sdk#128]
Hi admin,
I have just created a simple Android application using PowerAuth.
At MainActivity, after add dependency in my gradle.build (io.getlime.security.powerauth:powerauth-android-sdk:0.19.0) file and configure I call createActivation() method It returns null at onActivationCreateFailed(). I don't know the reason why. 
My mobile emulator display toast: "create fail: null"
My API server: powerauth-restful-server-spring 0.18.0
Here is my snippet ai Main activity: https://gist.github.com/HoaiNam1105/7930fe738a30b6f0d3b0d6ff3d76de54
And log: https://gist.github.com/HoaiNam1105/a983690adf97b2c92a01aa043d65238e
Any suggestion would be appreciated. Thank you in advance

**Comment by petrdvorak** [comment]
@HoaiNam1105 Could you please send us the server log as well? This will help us understand which part of the activation actually failed.

**Comment by HoaiNam1105** [comment]
this is my server log: https://gist.github.com/HoaiNam1105/750380388065aba7f2bcf643a7c6017a
thank you

**Comment by petrdvorak** [comment]
@HoaiNam1105 We need the other log from the other server. :)

Just to clarify - there are three actors during the activation process, that communicate with each other:

```
[MOBILE_APP] <= rest => [INTERMEDIATE_SERVER] <= soap => [POWERAUTH_SERVER]
```

The first exception you sent says that mobile app didn't complete the activation since intermediate server reported activation is invalid (this is a generic error message we use for any error). The second exception says that intermediate server (your app, basically) wasn't able to complete activation due to some error on PowerAuth Server. Only PowerAuth Server (the component that is usually hidden deep in the banking system infrastructure) contains a log with the exact nature of the error.

**Comment by HoaiNam1105** [comment]
Thanks for your suggestion, Recently I do not have [INTERMEDIATE_SERVER] yet so I call directly from standard RESTful API of PowerAuth server, Is it possible?. I assigned API_SERVER as this "http://localhost:8080/powerauth-restful-server-spring/" then I follow the guide https://github.com/wultra/powerauth-mobile-sdk/wiki/PowerAuth-SDK-for-Android

**Comment by petrdvorak** [comment]
@HoaiNam1105 There always need to be these three actors in some incarnation. In your setup, the "PowerAuth RESTful Server" acts in the role of "intermediate server application". But you still need the "PowerAuth Server" application behind it.

Basically:

1) Download and deploy PowerAuth Server from here:

https://github.com/wultra/powerauth-server/releases
https://github.com/wultra/powerauth-server/wiki/Deploying-PowerAuth-Server

2) After that, download and deploy PowerAuth RESTful API Server:

You need to build the server from the master branch - we currently use it as an example only and no longer ship it with the app: https://github.com/wultra/powerauth-restful-integration
https://github.com/wultra/powerauth-restful-integration/wiki/Deploying-PowerAuth-Standard-RESTful-API

Make sure that versions you deploy are compatible with each other:

https://github.com/wultra/powerauth-crypto/wiki/PowerAuth-2018.03

In case you needed a further help, please drop me a line and we could schedule a Skype call.

**Comment by hvge** [comment]
Hi @HoaiNam1105, you can also reach us on https://gitter.im/wultra/powerauth

Not a bug, so closing the issue.
