### ISSUE TITLE
iOS: return NSHTTPURLResponse in http requests

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-mobile-sdk#147]
`postToUrl` in `PA2Client` is returning `NSURLResponse` in completion block. It would be much more convenient to return `NSHTTPURLResponse` right away since the response is this type every time anyway.

**Comment by hvge** [comment]
I don't want to fix this. We're going to change this interface in Crypto 3.0 related works, so this change will just complicate things during the future merge. On top of that, `PA2Client` should not be used in applications for networking. Now, it's public interface, but I would rather make it private in the future SDK versions, than make it more usable from swift. 

But I'll consider this proposition in that crypto 3.0 major update.
