### ISSUE TITLE
Use custom exception object for SDK callbacks

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-mobile-sdk#18]
We currently have "failed" callback methods with `Throwable t` argument. This is not very handy, since developers need to use `instanceof` to check the exception type.

We should probably migrate all throwables in the top level SDK to our custom exception.

**Comment by petrdvorak** [comment]
After we fix this issue, we should send an e-mail echo about this change to the customer, since they might be relying on the `instanceof` code.

**Comment by hvge** [comment]
I decided to do not fix this issue. We're already using 4 different exception classes in SDK (it can be reduced to 3 base classes), so application has to handle at least two of our base types (`PowerAuthErrorException` and `FailedApiException`). It makes no sense to generalize this.

Once we decide to rewrite the library into Kotlin, then we'll have enough time to design the interface properly.
