### ISSUE TITLE
Accessibility of fingerprint dialog status messages

### ISSUE THREAD

**Issue by petrfuka** [wultra/powerauth-mobile-sdk#198]
Status messages on fingerprint dialog should send accessibility events so they can be reported by screen readers.

Current state: The screen reader correctly reports the dialog title and message. However, if an event occurs, it is not automatically reported.

For example, if authorization fails and the dialog shows the message "Fingerprint not recognized", that error message should be propagated to the accessibility API.

That should work for all relevant messages displayed to the user by the fingerprint dialog.

**Comment by petrdvorak** [comment]
@petrfuka Thank you for the report - this is related to wultra/powerauth-mobile-sdk#112 and mainly the new Android P unified biometry authentication. We will have a look...

**Comment by hvge** [comment]
Fixed for upcoming `1.2.0` release.
