### ISSUE TITLE
Insufficient proguard config causes crash

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-mobile-sdk#216]
SDK crashes when proguard is used.

Crash (anonymized with ■):
```
E/AndroidRuntime(11188): FATAL EXCEPTION: DefaultDispatcher-worker-4
E/AndroidRuntime(11188): Process: ■ ■ ■ ■ ■ ■ ■ ■ ■ ■, PID: 11188
E/AndroidRuntime(11188): java.lang.NoSuchMethodError: no non-static method "Lio/getlime/security/powerauth/core/EciesEncryptor;.<init>(J)V"
E/AndroidRuntime(11188):     at io.getlime.security.powerauth.core.Session.getEciesEncryptor(Native Method)
.
.
.
```

I managed to fix this with additional proguard rules on app side:
```
-keepclassmembers class io.getlime.security.powerauth.core.EciesEncryptor {
   <init>(...);
}
```

This should be fixed in SDK though, probably in https://github.com/wultra/powerauth-mobile-sdk/blob/develop/proj-android/PowerAuthLibrary/proguard-rules.pro where
```
-keep class io.getlime.security.powerauth.core.* {
    <fields>;
}
```
**should be replaced with**
```
-keep class io.getlime.security.powerauth.core.* {
    *;
}
```

**Comment by TomasKypta** [comment]
I guess 
```
-keep class io.getlime.security.powerauth.core.* {
    *;
}
```
is unnecessary, it's too general. It's always better to have ProGuard config *as minimal as possible*.

We have to keep things that are manipulated inside native. In our case it's class creation and filling of fields.
There are 8 classes that are created in native, 7 are in `io.getlime.security.powerauth.core` so we should change rule for `io.getlime.security.powerauth.core.*` to:
```
-keep class io.getlime.security.powerauth.core.* {
    <init>(...);
    <fields>;
}
```
The 8th is `Otp`, the rule should be:
```
-keep class io.getlime.security.powerauth.util.otp.Otp {
    <init>(...);
    <fields>;
}
```

Methods are not called in native, so there's no point in keeping all methods.
Note that rules for native methods are added by Android SDK's `proguard-android.txt`:
```
-keepclasseswithmembernames class * {
    native <methods>;
}
```

Remaining three rules in ProGuard configuration do not require any change.
Class `io.getlime.security.powerauth.sdk.impl.PowerAuthPrivateTokenData` is not created, only it's fields are accessed.
The two remaining rules `-keepclassmembers` are there for the json parsing and are not touched in native.
