### ISSUE TITLE
iOS 13 simulator forget persistent data

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-mobile-sdk#248]
It looks like that in the latest Xcode 11 (11A420a), the latest iOS simulator is unable to keep the persistent data in the keychain. The result is that the activation data is not present, or not available after the application restart.

This is the simulator problem and probably will be fixed by Apple later, but still, it's pain in the *ss, because the majority of our client's developers are using iOS simulator in regular basis.

**Comment by petrdvorak** [comment]
Quick question - do we have any insight on which specific part of the code is failing?

**Comment by hvge** [comment]
Yes, if there's `SecAccessControlRef` object in the query, then the simulator doesn't store the data and return the success. I've checked the underlying database (it's sqlite, so can be investigated) and there's really no data stored.

**Comment by petrdvorak** [comment]
Thank you.

**Comment by hvge** [comment]
Fix will be deployed to upcoming `1.2.0` & `1.3.0`, but I'll backport this change also to `0.20.x` & `1.1.x` branches.
