### ISSUE TITLE
Add support for Mac Catalyst platform

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-mobile-sdk#275]
We should prepare SDK for Mac Catalyst platform. As far as we know, the enhancement has the following implications:

- Precompiled OpenSSL
  - We should also update OpenSSL to the latest supported version
  - We should update build scripts and the release process, to download precompiled libraries from the cloud, to remove binaries from git.
- "cc7" library (only project update is required)
- "core" library (only project update is required)
- Investigate impact on "extensions SDKs" 
- Investigate "catalyst" support in cocoapods

**Comment by augard** [comment]
With all the news in latest WWDC, this should have high priority, when basically every iOS app will run on macOS in near future.

**Comment by petrdvorak** [comment]
@augard We have an open PR for this already, we were stopped in our efforts by broken Cocoapods...

https://github.com/wultra/powerauth-mobile-sdk/pull/299

**Comment by hvge** [comment]
Fixed by #320
