### ISSUE TITLE
Unable to setup biometry with commitActivationWithAuthentication

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-mobile-sdk#319]
On Android, when committing an activation with `PowerAuthAuthentication` object via `commitActivationWithAuthentication`, it's impossible to set up the biometry as the `authenticateUsingBiometry` public method (needed to fill the `useBiometry` property of the auth object) has always the `forceGenerate` parameter to `false` and will fail on missing key (obviously) since we're trying to create it in this situation.

**Comment by hvge** [comment]
I think that this is expected behavior. In case that you're using `commitActivationWithAuthentication` then it's up to application to manage the biometric related key. So, you can use low level objects from `io.getlime.security.powerauth.biometry` or application's custom code.

**Comment by kober32** [comment]
Oh, ok, I see that it is mentioned inside the documentation. Mmmmkay, I will use different API 👍
