### ISSUE TITLE
Allow accessing activation ID even before local commit

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-mobile-sdk#323]
Currently, we only allow accessing activation ID after the activation is locally committed. However, there are scenarios where this does not work - for example, if a commit is done after some action that depends on activation ID (i.e., sending OTP).

**Comment by hvge** [comment]
There's a similar problem with accessing `activationFingerprint`. You can get it in key-exchange response, but session's property implementation will not return it until commit.
