### ISSUE TITLE
Cocoapods 1.10 is failing to update PA to 1.4.3

### ISSUE THREAD

**Issue by augard** [wultra/powerauth-mobile-sdk#333]
`
[!] /bin/bash -c 
set -e
./scripts/ios-extensions-build.sh --out-dir Build release ios

ios-extensions-build.sh: -----------------------------------------------------------------------------
ios-extensions-build.sh: Compiling PA2Ext_Release...
ios-extensions-build.sh: -----------------------------------------------------------------------------
ios-extensions-build.sh: Executing build for scheme  PA2Ext_Release :: iphoneos
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: warning: class 'PowerAuthExtensionSDK' does not conform to protocol 'PA2SessionStatusProvider' [-Wprotocol]
@implementation PowerAuthExtensionSDK
                ^
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: note: add stubs for missing protocol requirements
@implementation PowerAuthExtensionSDK
                ^
1 warning generated.
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: warning: class 'PowerAuthExtensionSDK' does not conform to protocol 'PA2SessionStatusProvider' [-Wprotocol]
@implementation PowerAuthExtensionSDK
                ^
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: note: add stubs for missing protocol requirements
@implementation PowerAuthExtensionSDK
                ^
1 warning generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'PowerAuth2ForExtensions' from project 'PowerAuthExtensionSdk')
ios-extensions-build.sh: Executing build for scheme  PA2Ext_Release :: iphonesimulator
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: warning: class 'PowerAuthExtensionSDK' does not conform to protocol 'PA2SessionStatusProvider' [-Wprotocol]
@implementation PowerAuthExtensionSDK
                ^
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: note: add stubs for missing protocol requirements
@implementation PowerAuthExtensionSDK
                ^
1 warning generated.
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: warning: class 'PowerAuthExtensionSDK' does not conform to protocol 'PA2SessionStatusProvider' [-Wprotocol]
@implementation PowerAuthExtensionSDK
                ^
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: note: add stubs for missing protocol requirements
@implementation PowerAuthExtensionSDK
                ^
1 warning generated.
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: warning: class 'PowerAuthExtensionSDK' does not conform to protocol 'PA2SessionStatusProvider' [-Wprotocol]
@implementation PowerAuthExtensionSDK
                ^
/Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m:22:17: note: add stubs for missing protocol requirements
@implementation PowerAuthExtensionSDK
                ^
1 warning generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'PowerAuth2ForExtensions' from project 'PowerAuthExtensionSdk')
ios-extensions-build.sh: -----------------------------------------------------------------------------
ios-extensions-build.sh: FATalizing   PowerAuth2ForExtensions.framework
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/scripts/Tmp/PA2Ext_Release-iphoneos/Release-iphoneos/PowerAuth2ForExtensions.framework/PowerAuth2ForExtensions and /Users/lukas/Library/Caches/CocoaPods/Pods/Release/PowerAuth2ForExtensions/1.4.3-7f6e8/scripts/Tmp/PA2Ext_Release-iphonesimulator/Release-iphonesimulator/PowerAuth2ForExtensions.framework/PowerAuth2ForExtensions have the same architectures (arm64) and can't be in the same fat output file
`

**Comment by hvge** [comment]
We already addressed this in #320. Try `pod 'PowerAuth2', :git => 'https://github.com/wultra/powerauth-mobile-sdk.git', :branch => 'develop', :submodules => true` in your `Podfile` while we prepare a new release.

**Comment by hvge** [comment]
No response, so I'm assuming that my workaround is OK. Closing this issue.
