### ISSUE TITLE
Add method to remove previously set external encryption key

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-mobile-sdk#359]
Currently, we allow setting an "external encryption key" to an activation instance. This key is used to provide additional protection to some of the keys. The typical use-case is connecting the activation with some additional authentication mechanism, or implementing master-child activations.

However, there is currently no way to remove such additional protection from an existing activation, or to change the external encryption key.

**Comment by hvge** [comment]
Note that this is already implemented in low level Session, but has no public interface available in PowerAuthSDK. The only think that we need to wrap it to high level class and save the session's state after operation success.
