### ISSUE TITLE
Add method to return biometry related key

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-mobile-sdk#367]
Currently, we have `unlockBiometryKeysWithPrompt:withBlock:` which, however, returns the entire keychain contents. We should have a similar method only for the single biometry key.

**Comment by hvge** [comment]
Implemented as a new method in `PowerAuthSDK` object:
```objc
- (void) authenticateUsingBiometryWithPrompt:(nonnull NSString *)prompt
                                    callback:(nonnull void(^)(PowerAuthAuthentication * _Nullable authentication, NSError * _Nullable error))callback;
```
Backported to `1.5.x`
