### ISSUE TITLE
Get rid of openssl.xcframework in iOS SDK

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-mobile-sdk#371]
`openssl.xcframework` is so common among projects that it clashes with other libraries.

This is especially a problem in our [React native SDK](https://github.com/wultra/react-native-powerauth-mobile-sdk/issues/29).

**Comment by hvge** [comment]
This has to be a part of next release, due to breaking API changes. We have to split library into precompiled `PowerAuthCore` and high level `PowerAuth2`. I'll create an another task for that.

**Comment by hvge** [comment]
Closed by #373
