### ISSUE TITLE
Add init to the `PowerAuthUserInfo`

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-mobile-sdk#519]
The `UserInfo` class in java has a public construct but the obj-c counterpart does not. It would be nice to have it for iOS as well.

It would be even better if the iOS class implemented `NSCoding` and java `Parcelable` (or something similar) to have the possibility to store it to a byte array out-of-the-box (for caching purposes to Keychain and EncryptedSharedPreferences).

**Comment by hvge** [comment]
I'll just make the internal constructor public. The SDK has no use for such serialization, so it makes no sense to implement it.
