### ISSUE TITLE
Update Android dependencies and targetSdk to 33

### ISSUE THREAD

**Issue by TomasKypta** [wultra/powerauth-mobile-sdk#565]
Every Android apk released into Google Play has to be compiled with min target 33. 
The SDK should match that to ensure correct and expected funcionality in the final app. 

Dependencies of the SDK should be updated too (ideally to their latest versions) because they most like have older targets too.

**Comment by hvge** [comment]
I think we should backport this change also to `release/1.7.x` branch.
