### ISSUE TITLE
Missing `@Nullable` annotation in `ActivationStatus.getCustomObject`

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-mobile-sdk#578]
https://github.com/wultra/powerauth-mobile-sdk/blob/8c678891f3792ebaaa2be42f2ec18432bf8cfd32/proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ActivationStatus.java#L143

**Comment by hvge** [comment]
@kober32 do we have to backport this to 1.7.x?

**Comment by kober32** [comment]
Not necessary, I encountered this when doing something in react native wrapper, but it´s super minor...
