### ISSUE TITLE
Proguard and Error class

### ISSUE THREAD

**Issue by TheFaithOne** [wultra/powerauth-mobile-sdk#586]
During password validation process, we're using `ErrorResponseApiException` as a handle to fetch remaining attempts. This however doesn't work in a release build because of proguard. Returned throwable in the response for an invalid pin is:
`io.getlime.security.powerauth.networking.exceptions.FailedApiException: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: io.getlime.core.rest.model.base.entity.Error`

Adding keep rule in proguard for the specified class seems to resolve the issue. Would it be possible to add it to the consumer rules on your end or is this somehow an expected behavior?

Cheers

**Comment by hvge** [comment]
Thanks for your report. The fix will be available for 1.8.x and 1.7.x release branches.

**Comment by hvge** [comment]
@TheFaithOne Could you provide a snippet of code you use to extract such information? Additionally, your custom Proguard rule that solves the problem on your end would be helpful. Thank you.
