### ISSUE TITLE
Biometrics not working on multiple instances

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-mobile-sdk#620]
On Android, when multiple instances (with different instanceId) of `PowerAuthSDK` are created, signing with biometrics only works on the latest instance.

This is due to the shared biometric key, which is force-recreated when the biometrics factor is turned on (or activation is removed) making any biometrics already added on other instances invalid.

We should also consider adding documentation and tests that are working with multiple instances because many nuances when working in such a setup are undocumented and unexpected by default.

_Note: this is not an issue on iOS where this works correctly._

**Comment by hvge** [comment]
Raised bug to "critical", because it's already problematic in client's production.

**Comment by hvge** [comment]
The issue has to be fixed in the following release branches:

- `release/1.7.x` - the latest SDK supported in React Native wrapper
- `release/1.8.x`
- `release/1.9x` - upcoming release still in the development
